export const PRODUCTS = [
  // =========================
  // Rings
  // =========================

  {
    id: 1,
    imageId: 1,
    folder: "rings",
    category: "Rings",
    name: "Classic Sterling Silver Ring",
    price: 2499,
    originalPrice: 3299,
    rating: 4.9,
    reviewCount: 84,
    badge: "BESTSELLER",
    isBestSeller: true,
    isTrending: true,
    isNewArrival: false,
    isRecommended: true,
  },

  {
    id: 2,
    imageId: 2,
    folder: "rings",
    category: "Rings",
    name: "Minimal Band Ring",
    price: 1999,
    originalPrice: 2499,
    rating: 4.8,
    reviewCount: 42,
    badge: "NEW",
    isBestSeller: false,
    isTrending: false,
    isNewArrival: true,
    isRecommended: true,
  },

  {
    id: 3,
    imageId: 3,
    folder: "rings",
    category: "Rings",
    name: "Matte Finish Ring",
    price: 2299,
    originalPrice: 2899,
    rating: 4.7,
    reviewCount: 38,
    badge: null,
    isBestSeller: false,
    isTrending: true,
    isNewArrival: false,
    isRecommended: false,
  },

  {
    id: 4,
    imageId: 4,
    folder: "rings",
    category: "Rings",
    name: "Hammered Silver Ring",
    price: 2799,
    originalPrice: 3499,
    rating: 5.0,
    reviewCount: 91,
    badge: "LIMITED",
    isBestSeller: true,
    isTrending: false,
    isNewArrival: true,
    isRecommended: true,
  },

  // =========================
  // Chains
  // =========================

  {
    id: 5,
    imageId: 1,
    folder: "chains",
    category: "Chains",
    name: "Cuban Silver Chain",
    price: 4499,
    originalPrice: 5699,
    rating: 5.0,
    reviewCount: 162,
    badge: "BESTSELLER",
    isBestSeller: true,
    isTrending: true,
    isNewArrival: false,
    isRecommended: true,
  },

  {
    id: 6,
    imageId: 2,
    folder: "chains",
    category: "Chains",
    name: "Box Chain",
    price: 3999,
    originalPrice: 4999,
    rating: 4.8,
    reviewCount: 76,
    badge: "NEW",
    isBestSeller: false,
    isTrending: false,
    isNewArrival: true,
    isRecommended: true,
  },

  {
    id: 7,
    imageId: 3,
    folder: "chains",
    category: "Chains",
    name: "Rope Chain",
    price: 5299,
    originalPrice: 6499,
    rating: 4.9,
    reviewCount: 118,
    badge: null,
    isBestSeller: true,
    isTrending: true,
    isNewArrival: false,
    isRecommended: true,
  },

  {
    id: 8,
    imageId: 4,
    folder: "chains",
    category: "Chains",
    name: "Snake Chain",
    price: 4899,
    originalPrice: 5999,
    rating: 4.7,
    reviewCount: 53,
    badge: "NEW",
    isBestSeller: false,
    isTrending: false,
    isNewArrival: true,
    isRecommended: false,
  },

  // =========================
  // Bracelets
  // =========================

  {
    id: 9,
    imageId: 1,
    folder: "bracelets",
    category: "Bracelets",
    name: "Classic Silver Bracelet",
    price: 3299,
    originalPrice: 4199,
    rating: 4.9,
    reviewCount: 96,
    badge: "BESTSELLER",
    isBestSeller: true,
    isTrending: true,
    isNewArrival: false,
    isRecommended: true,
  },

  {
    id: 10,
    imageId: 2,
    folder: "bracelets",
    category: "Bracelets",
    name: "Cuban Bracelet",
    price: 3899,
    originalPrice: 4799,
    rating: 4.8,
    reviewCount: 61,
    badge: "NEW",
    isBestSeller: false,
    isTrending: false,
    isNewArrival: true,
    isRecommended: true,
  },

  {
    id: 11,
    imageId: 3,
    folder: "bracelets",
    category: "Bracelets",
    name: "Rope Bracelet",
    price: 3599,
    originalPrice: 4499,
    rating: 4.7,
    reviewCount: 44,
    badge: null,
    isBestSeller: false,
    isTrending: true,
    isNewArrival: false,
    isRecommended: false,
  },

  {
    id: 12,
    imageId: 4,
    folder: "bracelets",
    category: "Bracelets",
    name: "Figaro Bracelet",
    price: 4199,
    originalPrice: 5199,
    rating: 5.0,
    reviewCount: 103,
    badge: "LIMITED",
    isBestSeller: true,
    isTrending: false,
    isNewArrival: true,
    isRecommended: true,
  },

  // =========================
  // Earrings
  // =========================

  {
    id: 13,
    imageId: 1,
    folder: "earrings",
    category: "Earrings",
    name: "Sterling Silver Stud",
    price: 1499,
    originalPrice: 1999,
    rating: 4.8,
    reviewCount: 55,
    badge: "BESTSELLER",
    isBestSeller: true,
    isTrending: true,
    isNewArrival: false,
    isRecommended: true,
  },

  {
    id: 14,
    imageId: 2,
    folder: "earrings",
    category: "Earrings",
    name: "Minimal Hoop",
    price: 1799,
    originalPrice: 2299,
    rating: 4.7,
    reviewCount: 37,
    badge: "NEW",
    isBestSeller: false,
    isTrending: false,
    isNewArrival: true,
    isRecommended: true,
  },

  {
    id: 15,
    imageId: 3,
    folder: "earrings",
    category: "Earrings",
    name: "Cross Stud",
    price: 1699,
    originalPrice: 2199,
    rating: 4.8,
    reviewCount: 49,
    badge: null,
    isBestSeller: false,
    isTrending: true,
    isNewArrival: false,
    isRecommended: false,
  },

  {
    id: 16,
    imageId: 4,
    folder: "earrings",
    category: "Earrings",
    name: "Black Silver Hoop",
    price: 1999,
    originalPrice: 2599,
    rating: 4.9,
    reviewCount: 72,
    badge: "LIMITED",
    isBestSeller: true,
    isTrending: false,
    isNewArrival: true,
    isRecommended: true,
  },
];
